Traceback (most recent call last):
  File "c:\Users\lapto\AppData\Local\Programs\Python\Python313\Lib\site-packages\botasaurus_humancursor\web_adjuster.py", line 97, in move_to
    rect = element_or_pos._get_bounding_rect_with_iframe_offset()
  File "c:\Users\lapto\AppData\Local\Programs\Python\Python313\Lib\site-packages\botasaurus_driver\driver.py", line 218, in _get_bounding_rect_with_iframe_offset
    self_rect = self.get_bounding_rect()
  File "c:\Users\lapto\AppData\Local\Programs\Python\Python313\Lib\site-packages\botasaurus_driver\driver.py", line 232, in get_bounding_rect
    return self._elem.get_position(absolute)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "c:\Users\lapto\AppData\Local\Programs\Python\Python313\Lib\site-packages\botasaurus_driver\core\element.py", line 623, in get_position
    self.raise_if_disconnected()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "c:\Users\lapto\AppData\Local\Programs\Python\Python313\Lib\site-packages\botasaurus_driver\core\element.py", line 730, in raise_if_disconnected
    response = self.is_disconnected()
  File "c:\Users\lapto\AppData\Local\Programs\Python\Python313\Lib\site-packages\botasaurus_driver\core\element.py", line 736, in is_disconnected
    return self.apply('(el)=>!el.isConnected')
           ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\lapto\AppData\Local\Programs\Python\Python313\Lib\site-packages\botasaurus_driver\core\element.py", line 594, in apply
    self._remote_object = self._tab.send(
                          ~~~~~~~~~~~~~~^
        cdp.dom.resolve_node(backend_node_id=self.backend_node_id)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "c:\Users\lapto\AppData\Local\Programs\Python\Python313\Lib\site-packages\botasaurus_driver\core\connection.py", line 286, in send
    self.open()
    ~~~~~~~~~^^
  File "c:\Users\lapto\AppData\Local\Programs\Python\Python313\Lib\site-packages\botasaurus_driver\core\connection.py", line 167, in open
    self.wait_for_socket_connection()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "c:\Users\lapto\AppData\Local\Programs\Python\Python313\Lib\site-packages\botasaurus_driver\core\connection.py", line 190, in wait_for_socket_connection
    self.raise_connection_failure_exception()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "c:\Users\lapto\AppData\Local\Programs\Python\Python313\Lib\site-packages\botasaurus_driver\core\connection.py", line 182, in raise_connection_failure_exception
    raise Exception(self._connection_failure_message)
Exception: [WinError 10061] No connection could be made because the target machine actively refused it

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\lapto\AppData\Local\Programs\Python\Python313\Lib\site-packages\botasaurus\browser_decorator.py", line 201, in run_task
    result = func(driver, data)
  File "d:\mada\devlopment\botasaurus_whatsapp-main\whatsapp_automation.py", line 81, in open_whatsapp
    driver.wait_for_element(selector=json_data['send_button']).click()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "c:\Users\lapto\AppData\Local\Programs\Python\Python313\Lib\site-packages\botasaurus_driver\driver.py", line 291, in click
    self._driver._cursor.click(self, skip_move=skip_move)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\lapto\AppData\Local\Programs\Python\Python313\Lib\site-packages\botasaurus_humancursor\web_cursor.py", line 74, in click
    self.move_to(
    ~~~~~~~~~~~~^
        element,
        ^^^^^^^^
    ...<3 lines>...
        steady=steady
        ^^^^^^^^^^^^^
    )
    ^
  File "c:\Users\lapto\AppData\Local\Programs\Python\Python313\Lib\site-packages\botasaurus_humancursor\web_cursor.py", line 45, in move_to
    self.origin_coordinates = self.human.move_to(
                              ~~~~~~~~~~~~~~~~~~^
        element,
        ^^^^^^^^
    ...<6 lines>...
        is_mouse_pressed=is_mouse_pressed,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "c:\Users\lapto\AppData\Local\Programs\Python\Python313\Lib\site-packages\botasaurus_humancursor\web_adjuster.py", line 102, in move_to
    rect = self.driver.run_js("(function(el){var r=el.getBoundingClientRect(); return {x: r.x, y: r.y, width: r.width, height: r.height};})(arguments[0]);", [raw])
  File "c:\Users\lapto\AppData\Local\Programs\Python\Python313\Lib\site-packages\botasaurus_driver\driver.py", line 746, in run_js
    return self._tab.evaluate(script,args=args,await_promise=True)
           ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\lapto\AppData\Local\Programs\Python\Python313\Lib\site-packages\botasaurus_driver\core\tab.py", line 998, in evaluate
    core = make_core_string(expression, args)
  File "c:\Users\lapto\AppData\Local\Programs\Python\Python313\Lib\site-packages\botasaurus_driver\core\tab.py", line 36, in make_core_string
    expression = expression.replace("ARGS",  json.dumps(args).replace(r'\"', r'\\"'))
                                             ~~~~~~~~~~^^^^^^
  File "c:\Users\lapto\AppData\Local\Programs\Python\Python313\Lib\json\__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "c:\Users\lapto\AppData\Local\Programs\Python\Python313\Lib\json\encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "c:\Users\lapto\AppData\Local\Programs\Python\Python313\Lib\json\encoder.py", line 261, in iterencode
    return _iterencode(o, 0)
  File "c:\Users\lapto\AppData\Local\Programs\Python\Python313\Lib\json\encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
                    f'is not JSON serializable')
TypeError: Object of type Element is not JSON serializable
